In [25]:
from idlelib import history

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

from experiments import X_train

In [26]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [27]:
data.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace = True)

In [28]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [29]:
Le = LabelEncoder()
gen_le = Le.fit_transform(data['Gender'])
gen_le

array([0, 0, 0, ..., 0, 1, 0])

In [30]:
data['Gender'] = gen_le

In [31]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [32]:
ohe = OneHotEncoder()
geography = ohe.fit_transform(data[['Geography']]).toarray()
geo_col = ohe.get_feature_names_out(['Geography'])
df_geography = pd.DataFrame(geography, columns=geo_col)

In [35]:
df = pd.concat([data.drop(['Geography'],axis=1), df_geography], axis=1)
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [36]:
X = df.drop(['EstimatedSalary'], axis=1)
y = df['EstimatedSalary']

In [38]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [39]:
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [40]:
with open('ss_regression.pkl','wb') as f:
    pickle.dump(ss,f)
with open('ohe_regression.pkl','wb') as f:
    pickle.dump(ohe,f)
with open('Le_regression.pkl','wb') as f:
    pickle.dump(Le,f)

In [41]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

2026-05-24 22:33:57.425819: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [42]:
model = Sequential(
    [
        Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
        Dense(32,activation='relu'),
        Dense(1) # by defalut linear activation function
    ]
)

/Users/tabindahasif/Downloads/ANN Project/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [44]:
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

In [45]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [46]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime
log_dir = 'logs/fit/' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir)

In [47]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [48]:
history = model.fit(
    X_train, y_train, validation_data=(X_test, y_test), epochs=100,
    callbacks=[tensorboard_callback, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 100384.5469 - mae: 100384.5469 - val_loss: 98546.1328 - val_mae: 98546.1328
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99735.7188 - mae: 99735.7188 - val_loss: 97235.2266 - val_mae: 97235.2266
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 97443.8438 - mae: 97443.8438 - val_loss: 93868.4844 - val_mae: 93868.4844
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 92902.8828 - mae: 92902.8828 - val_loss: 88166.9062 - val_mae: 88166.9062
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 86144.1094 - mae: 86144.1094 - val_loss: 80549.1172 - val_mae: 80549.1172
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 77890.1719 - mae: 77890.1719 - val_loss: 72175.0469 - val_mae: 72175.0469
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 69516.3594 - mae: 69516.3594 - val_loss: 64485.1289 - val_mae: 64485.1289
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62098.0703 - mae: 62098.0703 - val_loss: 58241.8789 - val_mae: 58241.8789
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 56675.7695 - mae: 56675.7695 - val_loss: 54164.4570 - val_mae: 54164.4570
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53389.7031 - mae: 53389.7031 - val_loss: 51929.4688 - val_mae: 51929.4688
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 51652.5586 - mae: 51652.5586 - val_loss: 51024.2812 - val_mae: 51024.2812
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50899.9141 - mae: 50899.9141 - val_loss: 50709.7227 - val_mae: 50709.7227
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50581.1758 - mae: 50581.1758 - val_loss: 50587.5234 - val_mae: 50587.5234
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50411.5234 - mae: 50411.5234 - val_loss: 50533.1250 - val_mae: 50533.1250
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50317.4414 - mae: 50317.4414 - val_loss: 50487.5547 - val_mae: 50487.5547
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50250.5859 - mae: 50250.5859 - val_loss: 50446.3945 - val_mae: 50446.3945
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50188.6172 - mae: 50188.6172 - val_loss: 50407.0586 - val_mae: 50407.0586
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50138.0742 - mae: 50138.0742 - val_loss: 50375.5352 - val_mae: 50375.5352
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50093.1992 - mae: 50093.1992 - val_loss: 50344.1406 - val_mae: 50344.1406
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50052.8477 - mae: 50052.8477 - val_loss: 50310.6719 - val_mae: 50310.6719
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50013.6836 - mae: 50013.6836 - val_loss: 50295.8320 - val_mae: 50295.8320
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49979.2305 - mae: 49979.2305 - val_loss: 50267.4805 - val_mae: 50267.4805
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49948.1641 - mae: 49948.1641 - val_loss: 50248.0039 - val_mae: 50248.0039
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49917.4727 - mae: 49917.4727 - val_loss: 50232.4844 - val_mae: 50232.4844
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49892.8086 - mae: 49892.8086 - val_loss: 50214.9102 - val_mae: 50214.9102
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49865.9297 - mae: 49865.9297 - val_loss: 50199.5742 - val_mae: 50199.5742
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49843.3086 - mae: 49843.3086 - val_loss: 50183.7930 - val_mae: 50183.7930
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49821.7266 - mae: 49821.7266 - val_loss: 50180.5195 - val_mae: 50180.5195
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49805.0508 - mae: 49805.0508 - val_loss: 50168.6836 - val_mae: 50168.6836
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 49784.4805 - mae: 49784.4805 - val_loss: 50166.2266 - val_mae: 50166.2266
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49768.1523 - mae: 49768.1523 - val_loss: 50160.3203 - val_mae: 50160.3203
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 49750.1602 - mae: 49750.1602 - val_loss: 50154.5859 - val_mae: 50154.5859
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49736.5703 - mae: 49736.5703 - val_loss: 50146.8555 - val_mae: 50146.8555
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49722.8359 - mae: 49722.8359 - val_loss: 50150.1250 - val_mae: 50150.1250
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49708.0352 - mae: 49708.0352 - val_loss: 50141.1055 - val_mae: 50141.1055
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49696.5352 - mae: 49696.5352 - val_loss: 50136.3516 - val_mae: 50136.3516
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49682.4766 - mae: 49682.4766 - val_loss: 50129.4492 - val_mae: 50129.4492
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49670.7578 - mae: 49670.7578 - val_loss: 50139.6641 - val_mae: 50139.6641
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49663.1094 - mae: 49663.1094 - val_loss: 50128.3086 - val_mae: 50128.3086
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49645.3555 - mae: 49645.3555 - val_loss: 50121.2188 - val_mae: 50121.2188
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49638.4961 - mae: 49638.4961 - val_loss: 50109.6328 - val_mae: 50109.6328
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49627.7383 - mae: 49627.7383 - val_loss: 50111.3477 - val_mae: 50111.3477
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49615.2031 - mae: 49615.2031 - val_loss: 50113.3438 - val_mae: 50113.3438
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49603.9883 - mae: 49603.9883 - val_loss: 50109.8242 - val_mae: 50109.8242
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49595.5117 - mae: 49595.5117 - val_loss: 50107.3398 - val_mae: 50107.3398
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49587.9023 - mae: 49587.9023 - val_loss: 50103.7148 - val_mae: 50103.7148
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49577.2305 - mae: 49577.2305 - val_loss: 50106.0781 - val_mae: 50106.0781
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49569.9062 - mae: 49569.9062 - val_loss: 50113.2773 - val_mae: 50113.2773
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49559.9883 - mae: 49559.9883 - val_loss: 50106.9141 - val_mae: 50106.9141
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49552.1289 - mae: 49552.1289 - val_loss: 50092.4414 - val_mae: 50092.4414
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49549.5938 - mae: 49549.5938 - val_loss: 50102.3047 - val_mae: 50102.3047
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49538.0977 - mae: 49538.0977 - val_loss: 50101.4609 - val_mae: 50101.4609
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49531.5859 - mae: 49531.5859 - val_loss: 50099.9453 - val_mae: 50099.9453
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49524.7344 - mae: 49524.7344 - val_loss: 50101.0781 - val_mae: 50101.0781
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49520.1680 - mae: 49520.1680 - val_loss: 50100.0977 - val_mae: 50100.0977
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49512.7969 - mae: 49512.7969 - val_loss: 50084.5039 - val_mae: 50084.5039
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49506.4453 - mae: 49506.4453 - val_loss: 50091.2773 - val_mae: 50091.2773
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49498.9492 - mae: 49498.9492 - val_loss: 50093.4805 - val_mae: 50093.4805
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49492.8320 - mae: 49492.8320 - val_loss: 50082.2539 - val_mae: 50082.2539
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49491.9844 - mae: 49491.9844 - val_loss: 50086.3203 - val_mae: 50086.3203
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49478.8750 - mae: 49478.8750 - val_loss: 50090.2227 - val_mae: 50090.2227
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49476.0312 - mae: 49476.0312 - val_loss: 50095.1680 - val_mae: 50095.1680
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49468.3125 - mae: 49468.3125 - val_loss: 50093.9531 - val_mae: 50093.9531
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49466.0977 - mae: 49466.0977 - val_loss: 50087.0781 - val_mae: 50087.0781
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49460.5000 - mae: 49460.5000 - val_loss: 50086.4062 - val_mae: 50086.4062
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49454.6484 - mae: 49454.6484 - val_loss: 50085.2773 - val_mae: 50085.2773
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49447.7617 - mae: 49447.7617 - val_loss: 50099.1680 - val_mae: 50099.1680
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49445.0938 - mae: 49445.0938 - val_loss: 50101.2422 - val_mae: 50101.2422
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49436.4297 - mae: 49436.4297 - val_loss: 50102.5352 - val_mae: 50102.5352

In [55]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [56]:
%tensorboard --logdir ANN Project/logs/fit

ERROR: Failed to launch TensorBoard (exited with 2).
Contents of stderr:
2026-05-24 22:59:49.222661: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
usage: tensorboard [-h] [--helpfull] [--logdir PATH] [--logdir_spec PATH_SPEC]
                   [--host ADDR] [--bind_all] [--port PORT]
                   [--reuse_port BOOL] [--load_fast {false,auto,true}]
                   [--extra_data_server_flags EXTRA_DATA_SERVER_FLAGS]
                   [--grpc_creds_type {local,ssl,ssl_dev}]
                   [--grpc_data_provider PORT] [--purge_orphaned_data BOOL]
                   [--db URI] [--db_import] [--inspect] [--version_tb]
                   [--tag TAG] [--event_file PATH] [--path_prefix PATH]
                   [--window_title TEXT] [--max_reload_threads COUNT]
                   [--reload_interval SECONDS] [--reload_task TYPE]
                   [--reload_multifile BOOL]
                   [--reload_multifile_inactive_secs SECONDS]
                   [--generic_data TYPE]
                   [--samples_per_plugin SAMPLES_PER_PLUGIN]
                   [--detect_file_replacement BOOL]
                   {serve} ...
tensorboard: error: argument {serve}: invalid choice: 'Project/logs/fit' (choose from 'serve')

In [57]:
test_loss,test_mae = model.evaluate(X_test, y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50082.2539 - mae: 50082.2539

In [61]:
model.save('regression.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.